name: 🐛 Bug Report
description: Create a report to help us improve the plugin
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version
      description: Which version of Code Time Tracker are you using?
      placeholder: e.g. 0.8.6
    validations:
      required: true

  - type: input
    id: ide_version
    attributes:
      label: IDE Version
      description: Copy from "About IntelliJ IDEA" (e.g., IntelliJ IDEA 2024.2.3 Community)
      placeholder: e.g. IntelliJ IDEA 2024.3 Ultimate
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we make the bug happen again?
      placeholder: |
        1. Open a Java project
        2. Click on 'Code Statistics' tool window
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant logs or stack traces.
      render: shell